use super::{
    StdlibFunctionId, BASE64_ENCODING_DECODE_STRING, BASE64_ENCODING_ENCODE_TO_STRING,
    BASE64_RAW_STD_ENCODING_DECODE_STRING, BASE64_RAW_STD_ENCODING_ENCODE_TO_STRING,
    BASE64_RAW_URL_ENCODING_DECODE_STRING, BASE64_RAW_URL_ENCODING_ENCODE_TO_STRING,
    BASE64_STD_ENCODING_DECODE_STRING, BASE64_STD_ENCODING_ENCODE_TO_STRING,
    BASE64_URL_ENCODING_DECODE_STRING, BASE64_URL_ENCODING_ENCODE_TO_STRING, BUILTIN_CLEAR,
    BUILTIN_MAX, BUILTIN_MIN, BYTES_CLONE, BYTES_COMPARE, BYTES_CONTAINS, BYTES_CONTAINS_ANY,
    BYTES_CONTAINS_RUNE, BYTES_COUNT, BYTES_CUT, BYTES_CUT_PREFIX, BYTES_CUT_SUFFIX, BYTES_EQUAL,
    BYTES_EQUAL_FOLD, BYTES_FIELDS, BYTES_FIELDS_FUNC, BYTES_HAS_PREFIX, BYTES_HAS_SUFFIX,
    BYTES_INDEX, BYTES_INDEX_ANY, BYTES_INDEX_BYTE, BYTES_INDEX_FUNC, BYTES_INDEX_RUNE, BYTES_JOIN,
    BYTES_LAST_INDEX, BYTES_LAST_INDEX_ANY, BYTES_LAST_INDEX_BYTE, BYTES_LAST_INDEX_FUNC,
    BYTES_MAP, BYTES_REPEAT, BYTES_REPLACE, BYTES_REPLACE_ALL, BYTES_SPLIT, BYTES_SPLIT_AFTER,
    BYTES_SPLIT_AFTER_N, BYTES_SPLIT_N, BYTES_TO_LOWER, BYTES_TO_TITLE, BYTES_TO_UPPER, BYTES_TRIM,
    BYTES_TRIM_FUNC, BYTES_TRIM_LEFT, BYTES_TRIM_LEFT_FUNC, BYTES_TRIM_RIGHT,
    BYTES_TRIM_RIGHT_FUNC, BYTES_TRIM_SPACE, CMP_COMPARE, CMP_LESS, CMP_OR, CONTEXT_BACKGROUND,
    CONTEXT_DEADLINE, CONTEXT_DONE, CONTEXT_ERR, CONTEXT_INTERNAL_CANCEL, CONTEXT_TODO,
    CONTEXT_VALUE, CONTEXT_WITH_CANCEL, CONTEXT_WITH_DEADLINE, CONTEXT_WITH_TIMEOUT,
    CONTEXT_WITH_VALUE, ERRORS_AS, ERRORS_IS, ERRORS_JOIN, ERRORS_NEW, ERRORS_UNWRAP, FILEPATH_ABS,
    FILEPATH_BASE, FILEPATH_CLEAN, FILEPATH_DIR, FILEPATH_EXT, FILEPATH_FROM_SLASH, FILEPATH_GLOB,
    FILEPATH_IS_ABS, FILEPATH_IS_LOCAL, FILEPATH_JOIN, FILEPATH_LOCALIZE, FILEPATH_MATCH,
    FILEPATH_REL, FILEPATH_SPLIT, FILEPATH_SPLIT_LIST, FILEPATH_TO_SLASH, FILEPATH_VOLUME_NAME,
    FILEPATH_WALK, FILEPATH_WALK_DIR, HEX_DECODED_LEN, HEX_DECODE_STRING, HEX_ENCODED_LEN,
    HEX_ENCODE_TO_STRING, IO_FS_DIR_ENTRY_INFO, IO_FS_DIR_ENTRY_IS_DIR, IO_FS_DIR_ENTRY_NAME,
    IO_FS_DIR_ENTRY_TYPE, IO_FS_FILE_CLOSE, IO_FS_FILE_INFO_IS_DIR, IO_FS_FILE_INFO_MODE,
    IO_FS_FILE_INFO_MOD_TIME, IO_FS_FILE_INFO_NAME, IO_FS_FILE_INFO_SIZE, IO_FS_FILE_INFO_SYS,
    IO_FS_FILE_INFO_TO_DIR_ENTRY, IO_FS_FILE_MODE_IS_DIR, IO_FS_FILE_MODE_IS_REGULAR,
    IO_FS_FILE_MODE_PERM, IO_FS_FILE_MODE_STRING, IO_FS_FILE_MODE_TYPE, IO_FS_FILE_READ,
    IO_FS_FILE_STAT, IO_FS_FORMAT_DIR_ENTRY, IO_FS_FORMAT_FILE_INFO, IO_FS_FS_OPEN, IO_FS_GLOB,
    IO_FS_READ_DIR, IO_FS_READ_DIR_FILE_READ_DIR, IO_FS_READ_FILE, IO_FS_STAT, IO_FS_SUB,
    IO_FS_VALID_PATH, IO_FS_WALK_DIR, JSON_MARSHAL, JSON_MARSHAL_INDENT, JSON_UNMARSHAL,
    JSON_VALID, LOG_FATAL, LOG_FATALF, LOG_FLAGS, LOG_PREFIX, LOG_PRINT, LOG_PRINTF, LOG_PRINTLN,
    LOG_SET_FLAGS, LOG_SET_PREFIX, MAPS_CLONE, MAPS_COPY, MAPS_DELETE_FUNC, MAPS_EQUAL,
    MAPS_EQUAL_FUNC, MAPS_KEYS, MAPS_VALUES, MATH_ABS, MATH_ACOS, MATH_ASIN, MATH_ATAN, MATH_ATAN2,
    MATH_BITS_LEADING_ZEROS, MATH_BITS_LEN, MATH_BITS_ONES_COUNT, MATH_BITS_REVERSE,
    MATH_BITS_REVERSE_BYTES, MATH_BITS_ROTATE_LEFT, MATH_BITS_TRAILING_ZEROS, MATH_CBRT, MATH_CEIL,
    MATH_COPYSIGN, MATH_COS, MATH_COSH, MATH_DIM, MATH_EXP, MATH_EXPM1, MATH_FLOAT64_BITS,
    MATH_FLOAT64_FROM_BITS, MATH_FLOOR, MATH_FREXP, MATH_HYPOT, MATH_ILOGB, MATH_INF, MATH_IS_INF,
    MATH_IS_NAN, MATH_LDEXP, MATH_LOG, MATH_LOG10, MATH_LOG1P, MATH_LOG2, MATH_LOGB, MATH_MAX,
    MATH_MIN, MATH_MOD, MATH_MODF, MATH_NAN, MATH_POW, MATH_REMAINDER, MATH_ROUND, MATH_SIGNBIT,
    MATH_SIN, MATH_SINH, MATH_SQRT, MATH_TAN, MATH_TANH, MATH_TRUNC, MD5_SUM,
    NET_HTTP_CANONICAL_HEADER_KEY, NET_HTTP_CLIENT_DO, NET_HTTP_CLIENT_GET, NET_HTTP_CLIENT_HEAD,
    NET_HTTP_CLIENT_POST, NET_HTTP_CLIENT_POST_FORM, NET_HTTP_DETECT_CONTENT_TYPE, NET_HTTP_GET,
    NET_HTTP_HEAD, NET_HTTP_HEADER_ADD, NET_HTTP_HEADER_CLONE, NET_HTTP_HEADER_DEL,
    NET_HTTP_HEADER_GET, NET_HTTP_HEADER_SET, NET_HTTP_HEADER_VALUES, NET_HTTP_NEW_REQUEST,
    NET_HTTP_NEW_REQUEST_WITH_CONTEXT, NET_HTTP_PARSE_HTTP_VERSION, NET_HTTP_PARSE_TIME,
    NET_HTTP_POST, NET_HTTP_POST_FORM, NET_HTTP_REQUEST_BODY_READ, NET_HTTP_REQUEST_CLONE,
    NET_HTTP_REQUEST_CONTEXT, NET_HTTP_REQUEST_WITH_CONTEXT, NET_HTTP_RESPONSE_BODY_CLOSE,
    NET_HTTP_RESPONSE_BODY_READ, NET_HTTP_RESPONSE_LOCATION, NET_HTTP_STATUS_TEXT,
    NET_URL_JOIN_PATH, NET_URL_PARSE, NET_URL_PARSE_QUERY, NET_URL_PARSE_REQUEST_URI,
    NET_URL_PATH_ESCAPE, NET_URL_PATH_UNESCAPE, NET_URL_QUERY_ESCAPE, NET_URL_QUERY_UNESCAPE,
    NET_URL_URL_ESCAPED_FRAGMENT, NET_URL_URL_ESCAPED_PATH, NET_URL_URL_HOSTNAME,
    NET_URL_URL_IS_ABS, NET_URL_URL_JOIN_PATH, NET_URL_URL_MARSHAL_BINARY, NET_URL_URL_PARSE,
    NET_URL_URL_PORT, NET_URL_URL_QUERY, NET_URL_URL_REDACTED, NET_URL_URL_REQUEST_URI,
    NET_URL_URL_RESOLVE_REFERENCE, NET_URL_URL_STRING, NET_URL_URL_UNMARSHAL_BINARY, NET_URL_USER,
    NET_URL_USERINFO_PASSWORD, NET_URL_USERINFO_STRING, NET_URL_USERINFO_USERNAME,
    NET_URL_USER_PASSWORD, NET_URL_VALUES_ADD, NET_URL_VALUES_DEL, NET_URL_VALUES_ENCODE,
    NET_URL_VALUES_GET, NET_URL_VALUES_HAS, NET_URL_VALUES_SET, OS_CLEARENV, OS_DIR_FS, OS_ENVIRON,
    OS_EXECUTABLE, OS_EXIT, OS_EXPAND, OS_EXPAND_ENV, OS_GETEGID, OS_GETENV, OS_GETEUID, OS_GETGID,
    OS_GETGROUPS, OS_GETPAGESIZE, OS_GETPID, OS_GETPPID, OS_GETUID, OS_GETWD, OS_HOSTNAME,
    OS_IS_EXIST, OS_IS_NOT_EXIST, OS_IS_PATH_SEPARATOR, OS_IS_PERMISSION, OS_IS_TIMEOUT,
    OS_LOOKUP_ENV, OS_LSTAT, OS_MKDIR_ALL, OS_NEW_SYSCALL_ERROR, OS_READ_DIR, OS_READ_FILE,
    OS_REMOVE_ALL, OS_SAME_FILE, OS_SETENV, OS_STAT, OS_TEMP_DIR, OS_UNSETENV, OS_USER_CACHE_DIR,
    OS_USER_CONFIG_DIR, OS_USER_HOME_DIR, OS_WRITE_FILE, PATH_BASE, PATH_CLEAN, PATH_DIR, PATH_EXT,
    PATH_IS_ABS, PATH_JOIN, PATH_MATCH, PATH_SPLIT, RAND_FLOAT64, RAND_INT, RAND_INT31,
    RAND_INT31N, RAND_INT63, RAND_INT63N, RAND_INTN, RAND_SEED, REFLECT_KIND_STRING,
    REFLECT_STRUCT_TAG_GET, REFLECT_STRUCT_TAG_LOOKUP, REFLECT_TYPE_BITS, REFLECT_TYPE_COMPARABLE,
    REFLECT_TYPE_ELEM, REFLECT_TYPE_FIELD, REFLECT_TYPE_IN, REFLECT_TYPE_KEY, REFLECT_TYPE_KIND,
    REFLECT_TYPE_LEN, REFLECT_TYPE_NAME, REFLECT_TYPE_NUM_FIELD, REFLECT_TYPE_NUM_IN,
    REFLECT_TYPE_NUM_OUT, REFLECT_TYPE_OF, REFLECT_TYPE_OUT, REFLECT_TYPE_PKG_PATH,
    REFLECT_TYPE_STRING, REFLECT_VALUE_BOOL, REFLECT_VALUE_CAN_INTERFACE, REFLECT_VALUE_ELEM,
    REFLECT_VALUE_FIELD, REFLECT_VALUE_FLOAT, REFLECT_VALUE_INDEX, REFLECT_VALUE_INT,
    REFLECT_VALUE_INTERFACE, REFLECT_VALUE_IS_NIL, REFLECT_VALUE_IS_VALID, REFLECT_VALUE_KIND,
    REFLECT_VALUE_LEN, REFLECT_VALUE_MAP_INDEX, REFLECT_VALUE_MAP_KEYS, REFLECT_VALUE_NUM_FIELD,
    REFLECT_VALUE_OF, REFLECT_VALUE_STRING, REFLECT_VALUE_TYPE, REGEXP_COMPILE,
    REGEXP_MATCH_STRING, REGEXP_MUST_COMPILE, REGEXP_QUOTE_META, REGEXP_REGEXP_FIND_STRING,
    REGEXP_REGEXP_FIND_STRING_SUBMATCH, REGEXP_REGEXP_MATCH_STRING,
    REGEXP_REGEXP_REPLACE_ALL_STRING, REGEXP_REGEXP_SPLIT, SHA1_SUM, SHA256_SUM256, SHA512_SUM512,
    SLICES_COMPACT, SLICES_COMPACT_FUNC, SLICES_CONTAINS, SLICES_CONTAINS_FUNC, SLICES_EQUAL,
    SLICES_INDEX, SLICES_INDEX_FUNC, SLICES_REVERSE, SLICES_SORT_FUNC, SLICES_SORT_STABLE_FUNC,
    SORT_FLOAT64S, SORT_FLOAT64S_ARE_SORTED, SORT_INTS, SORT_INTS_ARE_SORTED, SORT_SEARCH,
    SORT_SEARCH_FLOAT64S, SORT_SEARCH_INTS, SORT_SEARCH_STRINGS, SORT_SLICE, SORT_SLICE_IS_SORTED,
    SORT_SLICE_STABLE, SORT_STRINGS, SORT_STRINGS_ARE_SORTED, STRCONV_ATOI, STRCONV_CAN_BACKQUOTE,
    STRCONV_FORMAT_BOOL, STRCONV_FORMAT_FLOAT, STRCONV_FORMAT_INT, STRCONV_FORMAT_UINT,
    STRCONV_ITOA, STRCONV_PARSE_BOOL, STRCONV_PARSE_FLOAT, STRCONV_PARSE_INT, STRCONV_PARSE_UINT,
    STRCONV_QUOTE, STRCONV_QUOTE_RUNE, STRCONV_QUOTE_RUNE_TO_ASCII, STRCONV_QUOTE_TO_ASCII,
    STRCONV_UNQUOTE, STRCONV_UNQUOTE_CHAR, STRINGS_CLONE, STRINGS_COMPARE, STRINGS_CONTAINS,
    STRINGS_CONTAINS_ANY, STRINGS_CONTAINS_RUNE, STRINGS_COUNT, STRINGS_CUT, STRINGS_CUT_PREFIX,
    STRINGS_CUT_SUFFIX, STRINGS_EQUAL_FOLD, STRINGS_FIELDS, STRINGS_FIELDS_FUNC,
    STRINGS_HAS_PREFIX, STRINGS_HAS_SUFFIX, STRINGS_INDEX, STRINGS_INDEX_ANY, STRINGS_INDEX_BYTE,
    STRINGS_INDEX_FUNC, STRINGS_INDEX_RUNE, STRINGS_JOIN, STRINGS_LAST_INDEX,
    STRINGS_LAST_INDEX_ANY, STRINGS_LAST_INDEX_BYTE, STRINGS_LAST_INDEX_FUNC, STRINGS_MAP,
    STRINGS_NEW_REPLACER, STRINGS_REPEAT, STRINGS_REPLACE, STRINGS_REPLACER_REPLACE,
    STRINGS_REPLACE_ALL, STRINGS_SPLIT, STRINGS_SPLIT_AFTER, STRINGS_SPLIT_AFTER_N,
    STRINGS_SPLIT_N, STRINGS_TO_LOWER, STRINGS_TO_TITLE, STRINGS_TO_UPPER, STRINGS_TRIM,
    STRINGS_TRIM_FUNC, STRINGS_TRIM_LEFT, STRINGS_TRIM_LEFT_FUNC, STRINGS_TRIM_PREFIX,
    STRINGS_TRIM_RIGHT, STRINGS_TRIM_RIGHT_FUNC, STRINGS_TRIM_SPACE, STRINGS_TRIM_SUFFIX,
    SYNC_MUTEX_LOCK, SYNC_MUTEX_UNLOCK, SYNC_ONCE_DO, SYNC_RW_MUTEX_LOCK, SYNC_RW_MUTEX_RLOCK,
    SYNC_RW_MUTEX_RUNLOCK, SYNC_RW_MUTEX_UNLOCK, SYNC_WAIT_GROUP_ADD, SYNC_WAIT_GROUP_DONE,
    SYNC_WAIT_GROUP_WAIT, TIME_AFTER, TIME_DURATION_HOURS, TIME_DURATION_MICROSECONDS,
    TIME_DURATION_MILLISECONDS, TIME_DURATION_MINUTES, TIME_DURATION_NANOSECONDS,
    TIME_DURATION_SECONDS, TIME_NEW_TIMER, TIME_NOW, TIME_PARSE, TIME_SINCE, TIME_SLEEP,
    TIME_TIMER_RESET, TIME_TIMER_STOP, TIME_TIME_ADD, TIME_TIME_AFTER, TIME_TIME_BEFORE,
    TIME_TIME_COMPARE, TIME_TIME_EQUAL, TIME_TIME_FORMAT, TIME_TIME_IS_ZERO, TIME_TIME_SUB,
    TIME_TIME_UNIX, TIME_TIME_UNIX_MICRO, TIME_TIME_UNIX_MILLI, TIME_TIME_UNIX_NANO, TIME_UNIX,
    TIME_UNIX_MICRO, TIME_UNIX_MILLI, TIME_UNTIL, UNICODE_IS_CONTROL, UNICODE_IS_DIGIT,
    UNICODE_IS_GRAPHIC, UNICODE_IS_LETTER, UNICODE_IS_LOWER, UNICODE_IS_MARK, UNICODE_IS_NUMBER,
    UNICODE_IS_PRINT, UNICODE_IS_PUNCT, UNICODE_IS_SPACE, UNICODE_IS_SYMBOL, UNICODE_IS_TITLE,
    UNICODE_IS_UPPER, UNICODE_SIMPLE_FOLD, UNICODE_TO, UNICODE_TO_LOWER, UNICODE_TO_TITLE,
    UNICODE_TO_UPPER, UTF8_DECODE_RUNE_IN_STRING, UTF8_FULL_RUNE_IN_STRING, UTF8_RUNE_COUNT,
    UTF8_RUNE_COUNT_IN_STRING, UTF8_RUNE_LEN, UTF8_VALID, UTF8_VALID_RUNE, UTF8_VALID_STRING,
};

#[path = "signatures_host.rs"]
mod host_impl;

const SYNC_NO_ARG_FUNC: &str = "__gowasm_func__()->()";

pub(super) fn stdlib_function_param_types(
    function: StdlibFunctionId,
) -> Option<&'static [&'static str]> {
    if let Some(types) = host_impl::stdlib_function_param_types_host(function) {
        return Some(types);
    }
    match function {
        CONTEXT_BACKGROUND | CONTEXT_TODO => Some(&[]),
        REFLECT_TYPE_OF => Some(&["interface{}"]),
        REFLECT_VALUE_OF => Some(&["interface{}"]),
        REFLECT_KIND_STRING => Some(&["reflect.Kind"]),
        REFLECT_STRUCT_TAG_GET | REFLECT_STRUCT_TAG_LOOKUP => {
            Some(&["reflect.StructTag", "string"])
        }
        REFLECT_TYPE_KIND
        | REFLECT_TYPE_STRING
        | REFLECT_TYPE_NAME
        | REFLECT_TYPE_PKG_PATH
        | REFLECT_TYPE_ELEM
        | REFLECT_TYPE_KEY
        | REFLECT_TYPE_LEN
        | REFLECT_TYPE_NUM_FIELD
        | REFLECT_TYPE_COMPARABLE
        | REFLECT_TYPE_BITS
        | REFLECT_TYPE_NUM_IN
        | REFLECT_TYPE_NUM_OUT => Some(&["reflect.__type"]),
        REFLECT_TYPE_FIELD | REFLECT_TYPE_IN | REFLECT_TYPE_OUT => Some(&["reflect.__type", "int"]),
        REFLECT_VALUE_KIND
        | REFLECT_VALUE_TYPE
        | REFLECT_VALUE_IS_VALID
        | REFLECT_VALUE_CAN_INTERFACE
        | REFLECT_VALUE_IS_NIL
        | REFLECT_VALUE_LEN
        | REFLECT_VALUE_NUM_FIELD
        | REFLECT_VALUE_BOOL
        | REFLECT_VALUE_INT
        | REFLECT_VALUE_FLOAT
        | REFLECT_VALUE_STRING
        | REFLECT_VALUE_ELEM
        | REFLECT_VALUE_MAP_KEYS
        | REFLECT_VALUE_INTERFACE => Some(&["reflect.__value"]),
        REFLECT_VALUE_INDEX | REFLECT_VALUE_FIELD => Some(&["reflect.__value", "int"]),
        REFLECT_VALUE_MAP_INDEX => Some(&["reflect.__value", "interface{}"]),
        CONTEXT_WITH_CANCEL => Some(&["context.Context"]),
        CONTEXT_WITH_DEADLINE => Some(&["context.Context", "time.Time"]),
        CONTEXT_WITH_TIMEOUT => Some(&["context.Context", "time.Duration"]),
        CONTEXT_WITH_VALUE => Some(&["context.Context", "interface{}", "interface{}"]),
        CONTEXT_INTERNAL_CANCEL => Some(&["context.Context"]),
        CONTEXT_DEADLINE => Some(&["context.__impl"]),
        CONTEXT_DONE => Some(&["context.__impl"]),
        CONTEXT_ERR => Some(&["context.__impl"]),
        CONTEXT_VALUE => Some(&["context.__impl", "interface{}"]),
        ERRORS_NEW => Some(&["string"]),
        ERRORS_JOIN => Some(&[]),
        ERRORS_UNWRAP => Some(&["error"]),
        ERRORS_IS => Some(&["error", "error"]),
        ERRORS_AS => Some(&["error", "any"]),
        LOG_SET_FLAGS => Some(&["int"]),
        LOG_FLAGS => Some(&[]),
        LOG_SET_PREFIX => Some(&["string"]),
        LOG_PREFIX | LOG_PRINTLN | LOG_PRINT | LOG_FATAL => Some(&[]),
        LOG_PRINTF | LOG_FATALF => Some(&["string"]),
        FILEPATH_BASE | FILEPATH_CLEAN | FILEPATH_DIR | FILEPATH_EXT | FILEPATH_TO_SLASH
        | FILEPATH_FROM_SLASH | FILEPATH_VOLUME_NAME | FILEPATH_IS_ABS | FILEPATH_IS_LOCAL
        | FILEPATH_SPLIT | FILEPATH_LOCALIZE | FILEPATH_ABS => Some(&["string"]),
        FILEPATH_SPLIT_LIST => Some(&["string"]),
        FILEPATH_JOIN => Some(&[]),
        FILEPATH_GLOB => Some(&["string"]),
        FILEPATH_WALK_DIR => Some(&[
            "string",
            "__gowasm_func__(string, fs.DirEntry, error)->(error)",
        ]),
        FILEPATH_MATCH | FILEPATH_REL => Some(&["string", "string"]),
        BASE64_ENCODING_ENCODE_TO_STRING => Some(&["*base64.Encoding", "[]byte"]),
        BASE64_ENCODING_DECODE_STRING => Some(&["*base64.Encoding", "string"]),
        PATH_BASE | PATH_CLEAN | PATH_DIR | PATH_EXT | PATH_IS_ABS | PATH_SPLIT => {
            Some(&["string"])
        }
        PATH_JOIN => Some(&[]),
        PATH_MATCH => Some(&["string", "string"]),
        SORT_INTS_ARE_SORTED => Some(&["[]int"]),
        SORT_STRINGS_ARE_SORTED => Some(&["[]string"]),
        SORT_FLOAT64S_ARE_SORTED => Some(&["[]float64"]),
        SORT_SEARCH_INTS => Some(&["[]int", "int"]),
        SORT_SEARCH_STRINGS => Some(&["[]string", "string"]),
        SORT_SEARCH_FLOAT64S => Some(&["[]float64", "float64"]),
        SORT_INTS => Some(&["[]int"]),
        SORT_STRINGS => Some(&["[]string"]),
        SORT_FLOAT64S => Some(&["[]float64"]),
        SORT_SLICE | SORT_SLICE_IS_SORTED | SORT_SLICE_STABLE => {
            Some(&["interface{}", "interface{}"])
        }
        SORT_SEARCH => Some(&["int", "interface{}"]),
        FILEPATH_WALK => Some(&[
            "string",
            "__gowasm_func__(string, fs.FileInfo, error)->(error)",
        ]),
        MATH_BITS_ONES_COUNT
        | MATH_BITS_LEADING_ZEROS
        | MATH_BITS_TRAILING_ZEROS
        | MATH_BITS_LEN
        | MATH_BITS_REVERSE
        | MATH_BITS_REVERSE_BYTES => Some(&["int"]),
        MATH_BITS_ROTATE_LEFT => Some(&["int", "int"]),
        UTF8_RUNE_COUNT_IN_STRING
        | UTF8_VALID_STRING
        | UTF8_FULL_RUNE_IN_STRING
        | UTF8_DECODE_RUNE_IN_STRING => Some(&["string"]),
        UTF8_RUNE_LEN | UTF8_VALID_RUNE => Some(&["int"]),
        UTF8_RUNE_COUNT | UTF8_VALID => Some(&["[]byte"]),
        REGEXP_COMPILE | REGEXP_MUST_COMPILE => Some(&["string"]),
        REGEXP_MATCH_STRING => Some(&["string", "string"]),
        REGEXP_REGEXP_MATCH_STRING
        | REGEXP_REGEXP_FIND_STRING
        | REGEXP_REGEXP_FIND_STRING_SUBMATCH => Some(&["*regexp.Regexp", "string"]),
        REGEXP_REGEXP_REPLACE_ALL_STRING => Some(&["*regexp.Regexp", "string", "string"]),
        REGEXP_REGEXP_SPLIT => Some(&["*regexp.Regexp", "string", "int"]),
        REGEXP_QUOTE_META => Some(&["string"]),
        STRINGS_CONTAINS | STRINGS_HAS_PREFIX | STRINGS_HAS_SUFFIX | STRINGS_COUNT
        | STRINGS_INDEX | STRINGS_LAST_INDEX | STRINGS_TRIM_PREFIX | STRINGS_TRIM_SUFFIX
        | STRINGS_CUT_PREFIX | STRINGS_CUT_SUFFIX | STRINGS_EQUAL_FOLD => {
            Some(&["string", "string"])
        }
        STRINGS_TRIM_SPACE | STRINGS_TO_UPPER | STRINGS_TO_LOWER | STRINGS_TO_TITLE
        | STRINGS_FIELDS | STRINGS_CLONE => Some(&["string"]),
        STRINGS_REPEAT => Some(&["string", "int"]),
        STRINGS_SPLIT
        | STRINGS_SPLIT_AFTER
        | STRINGS_CONTAINS_ANY
        | STRINGS_INDEX_ANY
        | STRINGS_LAST_INDEX_ANY => Some(&["string", "string"]),
        STRINGS_SPLIT_AFTER_N | STRINGS_SPLIT_N => Some(&["string", "string", "int"]),
        STRINGS_JOIN => Some(&["[]string", "string"]),
        STRINGS_NEW_REPLACER => Some(&[]),
        STRINGS_REPLACER_REPLACE => Some(&["*strings.Replacer", "string"]),
        STRINGS_TRIM | STRINGS_TRIM_LEFT | STRINGS_TRIM_RIGHT => Some(&["string", "string"]),
        STRINGS_CONTAINS_RUNE | STRINGS_INDEX_RUNE => Some(&["string", "int"]),
        STRINGS_COMPARE => Some(&["string", "string"]),
        STRINGS_REPLACE => Some(&["string", "string", "string", "int"]),
        STRINGS_REPLACE_ALL => Some(&["string", "string", "string"]),
        STRINGS_INDEX_BYTE | STRINGS_LAST_INDEX_BYTE => Some(&["string", "int"]),
        STRINGS_MAP => Some(&["interface{}", "string"]),
        STRINGS_INDEX_FUNC
        | STRINGS_LAST_INDEX_FUNC
        | STRINGS_TRIM_FUNC
        | STRINGS_TRIM_LEFT_FUNC
        | STRINGS_TRIM_RIGHT_FUNC
        | STRINGS_FIELDS_FUNC => Some(&["string", "interface{}"]),
        STRINGS_CUT => Some(&["string", "string"]),
        STRCONV_ITOA | STRCONV_QUOTE_RUNE | STRCONV_QUOTE_RUNE_TO_ASCII => Some(&["int"]),
        STRCONV_FORMAT_BOOL => Some(&["bool"]),
        STRCONV_CAN_BACKQUOTE => Some(&["string"]),
        STRCONV_QUOTE | STRCONV_QUOTE_TO_ASCII | STRCONV_UNQUOTE => Some(&["string"]),
        STRCONV_FORMAT_INT | STRCONV_FORMAT_UINT => Some(&["int", "int"]),
        STRCONV_ATOI | STRCONV_PARSE_BOOL => Some(&["string"]),
        STRCONV_PARSE_INT => Some(&["string", "int", "int"]),
        STRCONV_UNQUOTE_CHAR => Some(&["string", "int"]),
        STRCONV_FORMAT_FLOAT => Some(&["float64", "int", "int", "int"]),
        STRCONV_PARSE_FLOAT => Some(&["string", "int"]),
        STRCONV_PARSE_UINT => Some(&["string", "int", "int"]),
        UNICODE_IS_DIGIT | UNICODE_IS_LETTER | UNICODE_IS_SPACE | UNICODE_IS_UPPER
        | UNICODE_IS_LOWER | UNICODE_TO_UPPER | UNICODE_TO_LOWER | UNICODE_IS_NUMBER
        | UNICODE_IS_PRINT | UNICODE_IS_CONTROL | UNICODE_IS_GRAPHIC | UNICODE_IS_PUNCT
        | UNICODE_IS_SYMBOL | UNICODE_IS_MARK | UNICODE_IS_TITLE | UNICODE_TO_TITLE
        | UNICODE_SIMPLE_FOLD => Some(&["int"]),
        UNICODE_TO => Some(&["int", "int"]),
        MATH_ABS | MATH_CEIL | MATH_FLOOR | MATH_ROUND | MATH_SQRT | MATH_TRUNC | MATH_SIN
        | MATH_COS | MATH_TAN | MATH_LOG | MATH_LOG2 | MATH_LOG10 | MATH_EXP | MATH_IS_NAN
        | MATH_ASIN | MATH_ACOS | MATH_ATAN | MATH_SINH | MATH_COSH | MATH_TANH | MATH_SIGNBIT
        | MATH_EXPM1 | MATH_LOG1P | MATH_FREXP | MATH_CBRT | MATH_FLOAT64_BITS | MATH_LOGB
        | MATH_ILOGB | MATH_MODF => Some(&["float64"]),
        MATH_FLOAT64_FROM_BITS => Some(&["int"]),
        MATH_MAX | MATH_MIN | MATH_MOD | MATH_POW | MATH_ATAN2 | MATH_HYPOT | MATH_REMAINDER
        | MATH_DIM | MATH_COPYSIGN => Some(&["float64", "float64"]),
        MATH_INF => Some(&["int"]),
        MATH_NAN => Some(&[]),
        MATH_IS_INF | MATH_LDEXP => Some(&["float64", "int"]),
        RAND_INTN | RAND_INT63N | RAND_INT31N | RAND_SEED => Some(&["int"]),
        RAND_FLOAT64 | RAND_INT | RAND_INT63 | RAND_INT31 => Some(&[]),
        BYTES_CONTAINS | BYTES_EQUAL | BYTES_HAS_PREFIX | BYTES_HAS_SUFFIX | BYTES_INDEX
        | BYTES_LAST_INDEX | BYTES_COUNT | BYTES_COMPARE => Some(&["[]byte", "[]byte"]),
        BYTES_INDEX_BYTE | BYTES_LAST_INDEX_BYTE | BYTES_REPEAT | BYTES_INDEX_RUNE => {
            Some(&["[]byte", "int"])
        }
        BYTES_TRIM_SPACE | BYTES_TO_UPPER | BYTES_TO_LOWER | BYTES_FIELDS | BYTES_CLONE
        | BYTES_TO_TITLE => Some(&["[]byte"]),
        BYTES_JOIN => Some(&["[][]byte", "[]byte"]),
        BYTES_SPLIT | BYTES_SPLIT_AFTER | BYTES_CUT | BYTES_CUT_PREFIX | BYTES_CUT_SUFFIX
        | BYTES_EQUAL_FOLD => Some(&["[]byte", "[]byte"]),
        BYTES_SPLIT_N | BYTES_SPLIT_AFTER_N => Some(&["[]byte", "[]byte", "int"]),
        BYTES_REPLACE => Some(&["[]byte", "[]byte", "[]byte", "int"]),
        BYTES_REPLACE_ALL => Some(&["[]byte", "[]byte", "[]byte"]),
        BYTES_CONTAINS_ANY | BYTES_INDEX_ANY | BYTES_LAST_INDEX_ANY | BYTES_TRIM
        | BYTES_TRIM_LEFT | BYTES_TRIM_RIGHT => Some(&["[]byte", "string"]),
        BYTES_CONTAINS_RUNE => Some(&["[]byte", "int"]),
        BYTES_INDEX_FUNC
        | BYTES_LAST_INDEX_FUNC
        | BYTES_TRIM_FUNC
        | BYTES_TRIM_LEFT_FUNC
        | BYTES_TRIM_RIGHT_FUNC
        | BYTES_FIELDS_FUNC => Some(&["[]byte", "interface{}"]),
        BYTES_MAP => Some(&["interface{}", "[]byte"]),
        SLICES_CONTAINS | SLICES_INDEX => Some(&["interface{}", "interface{}"]),
        SLICES_CONTAINS_FUNC
        | SLICES_INDEX_FUNC
        | SLICES_SORT_FUNC
        | SLICES_SORT_STABLE_FUNC
        | SLICES_COMPACT_FUNC => Some(&["interface{}", "interface{}"]),
        SLICES_COMPACT | SLICES_REVERSE => Some(&["interface{}"]),
        SLICES_EQUAL => Some(&["interface{}", "interface{}"]),
        CMP_COMPARE | CMP_LESS => Some(&["interface{}", "interface{}"]),
        CMP_OR | BUILTIN_MIN | BUILTIN_MAX => Some(&[]),
        BUILTIN_CLEAR => Some(&["interface{}"]),
        MAPS_KEYS | MAPS_VALUES | MAPS_CLONE => Some(&["interface{}"]),
        MAPS_EQUAL | MAPS_COPY => Some(&["interface{}", "interface{}"]),
        MAPS_EQUAL_FUNC => Some(&["interface{}", "interface{}", "interface{}"]),
        MAPS_DELETE_FUNC => Some(&["interface{}", "interface{}"]),
        HEX_ENCODE_TO_STRING => Some(&["[]byte"]),
        HEX_DECODE_STRING => Some(&["string"]),
        HEX_ENCODED_LEN | HEX_DECODED_LEN => Some(&["int"]),
        BASE64_STD_ENCODING_ENCODE_TO_STRING
        | BASE64_URL_ENCODING_ENCODE_TO_STRING
        | BASE64_RAW_STD_ENCODING_ENCODE_TO_STRING
        | BASE64_RAW_URL_ENCODING_ENCODE_TO_STRING => Some(&["[]byte"]),
        BASE64_STD_ENCODING_DECODE_STRING
        | BASE64_URL_ENCODING_DECODE_STRING
        | BASE64_RAW_STD_ENCODING_DECODE_STRING
        | BASE64_RAW_URL_ENCODING_DECODE_STRING => Some(&["string"]),
        SYNC_WAIT_GROUP_ADD => Some(&["*sync.WaitGroup", "int"]),
        SYNC_WAIT_GROUP_DONE | SYNC_WAIT_GROUP_WAIT => Some(&["*sync.WaitGroup"]),
        SYNC_ONCE_DO => Some(&["*sync.Once", SYNC_NO_ARG_FUNC]),
        SYNC_MUTEX_LOCK | SYNC_MUTEX_UNLOCK => Some(&["*sync.Mutex"]),
        SYNC_RW_MUTEX_LOCK | SYNC_RW_MUTEX_UNLOCK | SYNC_RW_MUTEX_RLOCK | SYNC_RW_MUTEX_RUNLOCK => {
            Some(&["*sync.RWMutex"])
        }
        SHA256_SUM256 | MD5_SUM | SHA1_SUM | SHA512_SUM512 => Some(&["[]byte"]),
        _ => None,
    }
}

pub(super) fn stdlib_function_result_types(
    function: StdlibFunctionId,
) -> Option<&'static [&'static str]> {
    if let Some(types) = host_impl::stdlib_function_result_types_host(function) {
        return Some(types);
    }
    match function {
        CONTEXT_BACKGROUND | CONTEXT_TODO => Some(&["context.Context"]),
        REFLECT_TYPE_OF => Some(&["reflect.Type"]),
        REFLECT_VALUE_OF => Some(&["reflect.Value"]),
        REFLECT_KIND_STRING => Some(&["string"]),
        REFLECT_STRUCT_TAG_GET => Some(&["string"]),
        REFLECT_STRUCT_TAG_LOOKUP => Some(&["string", "bool"]),
        REFLECT_TYPE_KIND => Some(&["reflect.Kind"]),
        REFLECT_TYPE_STRING | REFLECT_TYPE_NAME | REFLECT_TYPE_PKG_PATH => Some(&["string"]),
        REFLECT_TYPE_ELEM | REFLECT_TYPE_KEY => Some(&["reflect.Type"]),
        REFLECT_TYPE_LEN
        | REFLECT_TYPE_NUM_FIELD
        | REFLECT_TYPE_BITS
        | REFLECT_TYPE_NUM_IN
        | REFLECT_TYPE_NUM_OUT => Some(&["int"]),
        REFLECT_TYPE_COMPARABLE => Some(&["bool"]),
        REFLECT_TYPE_IN | REFLECT_TYPE_OUT => Some(&["reflect.Type"]),
        REFLECT_TYPE_FIELD => Some(&["reflect.StructField"]),
        REFLECT_VALUE_KIND => Some(&["reflect.Kind"]),
        REFLECT_VALUE_TYPE => Some(&["reflect.Type"]),
        REFLECT_VALUE_IS_VALID
        | REFLECT_VALUE_CAN_INTERFACE
        | REFLECT_VALUE_IS_NIL
        | REFLECT_VALUE_BOOL => Some(&["bool"]),
        REFLECT_VALUE_LEN | REFLECT_VALUE_NUM_FIELD | REFLECT_VALUE_INT => Some(&["int"]),
        REFLECT_VALUE_FLOAT => Some(&["float64"]),
        REFLECT_VALUE_STRING => Some(&["string"]),
        REFLECT_VALUE_ELEM
        | REFLECT_VALUE_INDEX
        | REFLECT_VALUE_FIELD
        | REFLECT_VALUE_MAP_INDEX => Some(&["reflect.Value"]),
        REFLECT_VALUE_MAP_KEYS => Some(&["[]reflect.Value"]),
        REFLECT_VALUE_INTERFACE => Some(&["interface{}"]),
        CONTEXT_WITH_CANCEL | CONTEXT_WITH_DEADLINE | CONTEXT_WITH_TIMEOUT => {
            Some(&["context.Context", "context.CancelFunc"])
        }
        CONTEXT_WITH_VALUE => Some(&["context.Context"]),
        CONTEXT_DEADLINE => Some(&["time.Time", "bool"]),
        CONTEXT_DONE => Some(&["<-chan struct{}"]),
        CONTEXT_ERR => Some(&["error"]),
        CONTEXT_VALUE => Some(&["interface{}"]),
        ERRORS_NEW | ERRORS_JOIN | ERRORS_UNWRAP => Some(&["error"]),
        ERRORS_IS | ERRORS_AS => Some(&["bool"]),
        LOG_SET_FLAGS | LOG_SET_PREFIX | LOG_PRINTLN | LOG_PRINTF | LOG_PRINT | LOG_FATAL
        | LOG_FATALF => Some(&[]),
        LOG_FLAGS => Some(&["int"]),
        LOG_PREFIX => Some(&["string"]),
        FILEPATH_BASE | FILEPATH_CLEAN | FILEPATH_DIR | FILEPATH_EXT | FILEPATH_JOIN
        | FILEPATH_TO_SLASH | FILEPATH_FROM_SLASH | FILEPATH_VOLUME_NAME => Some(&["string"]),
        FILEPATH_IS_ABS | FILEPATH_IS_LOCAL => Some(&["bool"]),
        FILEPATH_GLOB => Some(&["[]string", "error"]),
        FILEPATH_LOCALIZE | FILEPATH_ABS => Some(&["string", "error"]),
        FILEPATH_MATCH => Some(&["bool", "error"]),
        FILEPATH_REL => Some(&["string", "error"]),
        FILEPATH_SPLIT => Some(&["string", "string"]),
        FILEPATH_SPLIT_LIST => Some(&["[]string"]),
        FILEPATH_WALK | FILEPATH_WALK_DIR => Some(&["error"]),
        PATH_BASE | PATH_CLEAN | PATH_DIR | PATH_EXT | PATH_JOIN => Some(&["string"]),
        PATH_IS_ABS => Some(&["bool"]),
        PATH_MATCH => Some(&["bool", "error"]),
        PATH_SPLIT => Some(&["string", "string"]),
        SORT_INTS_ARE_SORTED
        | SORT_STRINGS_ARE_SORTED
        | SORT_FLOAT64S_ARE_SORTED
        | SORT_SLICE_IS_SORTED => Some(&["bool"]),
        SORT_SEARCH_INTS | SORT_SEARCH_STRINGS | SORT_SEARCH_FLOAT64S | SORT_SEARCH => {
            Some(&["int"])
        }
        STRINGS_CONTAINS
        | STRINGS_HAS_PREFIX
        | STRINGS_HAS_SUFFIX
        | STRINGS_CONTAINS_ANY
        | STRINGS_CONTAINS_RUNE
        | STRINGS_EQUAL_FOLD => Some(&["bool"]),
        STRINGS_TRIM_SPACE
        | STRINGS_TO_UPPER
        | STRINGS_TO_LOWER
        | STRINGS_TO_TITLE
        | STRINGS_REPEAT
        | STRINGS_JOIN
        | STRINGS_TRIM_PREFIX
        | STRINGS_TRIM_SUFFIX
        | STRINGS_TRIM_LEFT
        | STRINGS_TRIM_RIGHT
        | STRINGS_TRIM
        | STRINGS_REPLACE_ALL
        | STRINGS_CLONE
        | STRINGS_REPLACE
        | STRINGS_MAP
        | STRINGS_TRIM_FUNC
        | STRINGS_TRIM_LEFT_FUNC
        | STRINGS_TRIM_RIGHT_FUNC => Some(&["string"]),
        STRINGS_COUNT
        | STRINGS_INDEX
        | STRINGS_LAST_INDEX
        | STRINGS_INDEX_ANY
        | STRINGS_LAST_INDEX_ANY
        | STRINGS_INDEX_RUNE
        | STRINGS_COMPARE
        | STRINGS_INDEX_BYTE
        | STRINGS_LAST_INDEX_BYTE
        | STRINGS_INDEX_FUNC
        | STRINGS_LAST_INDEX_FUNC => Some(&["int"]),
        STRINGS_SPLIT
        | STRINGS_SPLIT_AFTER
        | STRINGS_SPLIT_AFTER_N
        | STRINGS_SPLIT_N
        | STRINGS_FIELDS
        | STRINGS_FIELDS_FUNC => Some(&["[]string"]),
        STRINGS_NEW_REPLACER => Some(&["*strings.Replacer"]),
        STRINGS_CUT_PREFIX | STRINGS_CUT_SUFFIX => Some(&["string", "bool"]),
        STRINGS_CUT => Some(&["string", "string", "bool"]),
        STRINGS_REPLACER_REPLACE => Some(&["string"]),
        STRCONV_ITOA
        | STRCONV_FORMAT_BOOL
        | STRCONV_QUOTE
        | STRCONV_FORMAT_INT
        | STRCONV_FORMAT_UINT
        | STRCONV_QUOTE_TO_ASCII
        | STRCONV_QUOTE_RUNE_TO_ASCII
        | STRCONV_QUOTE_RUNE
        | STRCONV_FORMAT_FLOAT => Some(&["string"]),
        STRCONV_CAN_BACKQUOTE => Some(&["bool"]),
        STRCONV_ATOI => Some(&["int", "error"]),
        STRCONV_PARSE_BOOL => Some(&["bool", "error"]),
        STRCONV_PARSE_INT => Some(&["int", "error"]),
        STRCONV_UNQUOTE => Some(&["string", "error"]),
        STRCONV_PARSE_FLOAT => Some(&["float64", "error"]),
        STRCONV_PARSE_UINT => Some(&["int", "error"]),
        STRCONV_UNQUOTE_CHAR => Some(&["int", "bool", "string", "error"]),
        UNICODE_IS_DIGIT | UNICODE_IS_LETTER | UNICODE_IS_SPACE | UNICODE_IS_UPPER
        | UNICODE_IS_LOWER | UNICODE_IS_NUMBER | UNICODE_IS_PRINT | UNICODE_IS_GRAPHIC
        | UNICODE_IS_PUNCT | UNICODE_IS_SYMBOL | UNICODE_IS_MARK | UNICODE_IS_TITLE
        | UNICODE_IS_CONTROL => Some(&["bool"]),
        UNICODE_TO_UPPER | UNICODE_TO_LOWER | UNICODE_TO_TITLE | UNICODE_SIMPLE_FOLD
        | UNICODE_TO => Some(&["int"]),
        MATH_ABS | MATH_CEIL | MATH_FLOOR | MATH_MAX | MATH_MIN | MATH_MOD | MATH_POW
        | MATH_ROUND | MATH_SQRT | MATH_TRUNC | MATH_SIN | MATH_COS | MATH_TAN | MATH_LOG
        | MATH_LOG2 | MATH_LOG10 | MATH_EXP | MATH_ATAN2 | MATH_HYPOT | MATH_INF | MATH_NAN
        | MATH_ASIN | MATH_ACOS | MATH_ATAN | MATH_SINH | MATH_COSH | MATH_TANH
        | MATH_REMAINDER | MATH_DIM | MATH_COPYSIGN | MATH_LDEXP | MATH_EXPM1 | MATH_LOG1P => {
            Some(&["float64"])
        }
        MATH_IS_NAN | MATH_IS_INF | MATH_SIGNBIT => Some(&["bool"]),
        MATH_FREXP => Some(&["float64", "int"]),
        MATH_MODF => Some(&["float64", "float64"]),
        MATH_FLOAT64_BITS | MATH_ILOGB => Some(&["int"]),
        MATH_FLOAT64_FROM_BITS | MATH_CBRT | MATH_LOGB => Some(&["float64"]),
        RAND_INTN | RAND_INT | RAND_INT63 | RAND_INT63N | RAND_INT31 | RAND_INT31N => {
            Some(&["int"])
        }
        RAND_FLOAT64 => Some(&["float64"]),
        BYTES_CONTAINS | BYTES_EQUAL | BYTES_HAS_PREFIX | BYTES_HAS_SUFFIX | SLICES_CONTAINS
        | SLICES_CONTAINS_FUNC | SLICES_EQUAL | MAPS_EQUAL | MAPS_EQUAL_FUNC | CMP_LESS => {
            Some(&["bool"])
        }
        BYTES_INDEX
        | BYTES_LAST_INDEX
        | BYTES_INDEX_BYTE
        | BYTES_LAST_INDEX_BYTE
        | BYTES_COUNT
        | BYTES_COMPARE
        | BYTES_INDEX_ANY
        | BYTES_LAST_INDEX_ANY
        | BYTES_INDEX_RUNE
        | BYTES_INDEX_FUNC
        | BYTES_LAST_INDEX_FUNC
        | SLICES_INDEX
        | SLICES_INDEX_FUNC
        | CMP_COMPARE => Some(&["int"]),
        BYTES_REPEAT
        | BYTES_JOIN
        | BYTES_REPLACE
        | BYTES_REPLACE_ALL
        | BYTES_TRIM_SPACE
        | BYTES_TO_UPPER
        | BYTES_TO_LOWER
        | BYTES_CLONE
        | BYTES_TO_TITLE
        | BYTES_TRIM
        | BYTES_TRIM_LEFT
        | BYTES_TRIM_RIGHT
        | BYTES_TRIM_FUNC
        | BYTES_TRIM_LEFT_FUNC
        | BYTES_TRIM_RIGHT_FUNC
        | BYTES_MAP => Some(&["[]byte"]),
        BYTES_SPLIT | BYTES_SPLIT_N | BYTES_SPLIT_AFTER | BYTES_SPLIT_AFTER_N | BYTES_FIELDS
        | BYTES_FIELDS_FUNC => Some(&["[][]byte"]),
        BYTES_CONTAINS_ANY | BYTES_CONTAINS_RUNE | BYTES_EQUAL_FOLD => Some(&["bool"]),
        BYTES_CUT_PREFIX | BYTES_CUT_SUFFIX => Some(&["[]byte", "bool"]),
        BYTES_CUT => Some(&["[]byte", "[]byte", "bool"]),
        MATH_BITS_ONES_COUNT
        | MATH_BITS_LEADING_ZEROS
        | MATH_BITS_TRAILING_ZEROS
        | MATH_BITS_LEN
        | MATH_BITS_ROTATE_LEFT
        | MATH_BITS_REVERSE
        | MATH_BITS_REVERSE_BYTES => Some(&["int"]),
        UTF8_RUNE_COUNT_IN_STRING | UTF8_RUNE_LEN | UTF8_RUNE_COUNT => Some(&["int"]),
        UTF8_VALID_STRING | UTF8_VALID_RUNE | UTF8_VALID | UTF8_FULL_RUNE_IN_STRING => {
            Some(&["bool"])
        }
        UTF8_DECODE_RUNE_IN_STRING => Some(&["int", "int"]),
        REGEXP_COMPILE => Some(&["*regexp.Regexp", "error"]),
        REGEXP_MATCH_STRING => Some(&["bool", "error"]),
        REGEXP_REGEXP_MATCH_STRING => Some(&["bool"]),
        REGEXP_MUST_COMPILE => Some(&["*regexp.Regexp"]),
        REGEXP_REGEXP_FIND_STRING | REGEXP_REGEXP_REPLACE_ALL_STRING => Some(&["string"]),
        REGEXP_REGEXP_FIND_STRING_SUBMATCH | REGEXP_REGEXP_SPLIT => Some(&["[]string"]),
        SYNC_WAIT_GROUP_ADD
        | SYNC_WAIT_GROUP_DONE
        | SYNC_WAIT_GROUP_WAIT
        | SYNC_ONCE_DO
        | SYNC_MUTEX_LOCK
        | SYNC_MUTEX_UNLOCK
        | SYNC_RW_MUTEX_LOCK
        | SYNC_RW_MUTEX_UNLOCK
        | SYNC_RW_MUTEX_RLOCK
        | SYNC_RW_MUTEX_RUNLOCK => Some(&[]),
        REGEXP_QUOTE_META => Some(&["string"]),
        HEX_ENCODE_TO_STRING => Some(&["string"]),
        HEX_DECODE_STRING => Some(&["[]byte", "error"]),
        HEX_ENCODED_LEN | HEX_DECODED_LEN => Some(&["int"]),
        BASE64_ENCODING_ENCODE_TO_STRING => Some(&["string"]),
        BASE64_STD_ENCODING_ENCODE_TO_STRING
        | BASE64_URL_ENCODING_ENCODE_TO_STRING
        | BASE64_RAW_STD_ENCODING_ENCODE_TO_STRING
        | BASE64_RAW_URL_ENCODING_ENCODE_TO_STRING => Some(&["string"]),
        BASE64_ENCODING_DECODE_STRING => Some(&["[]byte", "error"]),
        BASE64_STD_ENCODING_DECODE_STRING
        | BASE64_URL_ENCODING_DECODE_STRING
        | BASE64_RAW_STD_ENCODING_DECODE_STRING
        | BASE64_RAW_URL_ENCODING_DECODE_STRING => Some(&["[]byte", "error"]),
        SHA256_SUM256 => Some(&["[32]byte"]),
        MD5_SUM => Some(&["[16]byte"]),
        SHA1_SUM => Some(&["[20]byte"]),
        SHA512_SUM512 => Some(&["[64]byte"]),
        _ => None,
    }
}

pub(super) fn stdlib_function_variadic_param_type(
    function: StdlibFunctionId,
) -> Option<&'static str> {
    if let Some(typ) = host_impl::stdlib_function_variadic_param_type_host(function) {
        return Some(typ);
    }
    match function {
        ERRORS_JOIN => Some("error"),
        LOG_PRINTLN | LOG_PRINTF | LOG_PRINT | LOG_FATAL | LOG_FATALF => Some("interface{}"),
        FILEPATH_JOIN => Some("string"),
        PATH_JOIN => Some("string"),
        CMP_OR | BUILTIN_MIN | BUILTIN_MAX => Some("interface{}"),
        STRINGS_NEW_REPLACER => Some("string"),
        _ => None,
    }
}
