use gowasm_lexer::TokenKind;

pub(crate) fn describe_token(kind: &TokenKind) -> String {
    match kind {
        TokenKind::Package => "`package`".into(),
        TokenKind::Import => "`import`".into(),
        TokenKind::Type => "`type`".into(),
        TokenKind::Const => "`const`".into(),
        TokenKind::Struct => "`struct`".into(),
        TokenKind::Interface => "`interface`".into(),
        TokenKind::Map => "`map`".into(),
        TokenKind::Chan => "`chan`".into(),
        TokenKind::Func => "`func`".into(),
        TokenKind::Var => "`var`".into(),
        TokenKind::If => "`if`".into(),
        TokenKind::Else => "`else`".into(),
        TokenKind::For => "`for`".into(),
        TokenKind::Range => "`range`".into(),
        TokenKind::Switch => "`switch`".into(),
        TokenKind::Select => "`select`".into(),
        TokenKind::Case => "`case`".into(),
        TokenKind::Default => "`default`".into(),
        TokenKind::Break => "`break`".into(),
        TokenKind::Continue => "`continue`".into(),
        TokenKind::Fallthrough => "`fallthrough`".into(),
        TokenKind::Return => "`return`".into(),
        TokenKind::Go => "`go`".into(),
        TokenKind::Defer => "`defer`".into(),
        TokenKind::True => "`true`".into(),
        TokenKind::False => "`false`".into(),
        TokenKind::Nil => "`nil`".into(),
        TokenKind::Ident(name) => format!("identifier `{name}`"),
        TokenKind::Int(value) => format!("integer `{value}`"),
        TokenKind::Float(bits) => format!("float `{}`", f64::from_bits(*bits)),
        TokenKind::String(value) => format!("string `{value}`"),
        TokenKind::LParen => "`(`".into(),
        TokenKind::RParen => "`)`".into(),
        TokenKind::LBracket => "`[`".into(),
        TokenKind::RBracket => "`]`".into(),
        TokenKind::LBrace => "`{`".into(),
        TokenKind::RBrace => "`}`".into(),
        TokenKind::Dot => "`.`".into(),
        TokenKind::Ellipsis => "`...`".into(),
        TokenKind::Comma => "`,`".into(),
        TokenKind::Colon => "`:`".into(),
        TokenKind::PlusPlus => "`++`".into(),
        TokenKind::PlusEqual => "`+=`".into(),
        TokenKind::Plus => "`+`".into(),
        TokenKind::MinusMinus => "`--`".into(),
        TokenKind::MinusEqual => "`-=`".into(),
        TokenKind::Minus => "`-`".into(),
        TokenKind::StarEqual => "`*=`".into(),
        TokenKind::Star => "`*`".into(),
        TokenKind::SlashEqual => "`/=`".into(),
        TokenKind::Slash => "`/`".into(),
        TokenKind::PercentEqual => "`%=`".into(),
        TokenKind::Percent => "`%`".into(),
        TokenKind::ColonEqual => "`:=`".into(),
        TokenKind::Bang => "`!`".into(),
        TokenKind::Equal => "`=`".into(),
        TokenKind::EqualEqual => "`==`".into(),
        TokenKind::BangEqual => "`!=`".into(),
        TokenKind::CaretEqual => "`^=`".into(),
        TokenKind::Caret => "`^`".into(),
        TokenKind::AndAnd => "`&&`".into(),
        TokenKind::BitAndEqual => "`&=`".into(),
        TokenKind::BitAnd => "`&`".into(),
        TokenKind::BitClear => "`&^`".into(),
        TokenKind::BitOrEqual => "`|=`".into(),
        TokenKind::BitOr => "`|`".into(),
        TokenKind::Arrow => "`<-`".into(),
        TokenKind::OrOr => "`||`".into(),
        TokenKind::ShiftLeftEqual => "`<<=`".into(),
        TokenKind::ShiftLeft => "`<<`".into(),
        TokenKind::ShiftRightEqual => "`>>=`".into(),
        TokenKind::ShiftRight => "`>>`".into(),
        TokenKind::Less => "`<`".into(),
        TokenKind::LessEqual => "`<=`".into(),
        TokenKind::Greater => "`>`".into(),
        TokenKind::GreaterEqual => "`>=`".into(),
        TokenKind::Semicolon => "`;`".into(),
        TokenKind::Eof => "end of file".into(),
    }
}
